spring:
  application:
    name: sb-zuul #该项目名

server:
  host: localhost
  port: 7061


zuul:
  routes:
    sb-provider: /zuul-demo/**  #注意匹配名不能叫zuul，会和关键字冲突，匹配不到

eureka:
  client:
    #将此项目注册到Eureka服务
    register-with-eureka: true
    service-url:
      defaultZone: http://root:root@localhost:7001/eureka


