spring:
  application:
    name: ribbon-consumer
server:
  port: 5001

eureka:
  client:
    register-with-eureka: true
    service-url:
      defaultZone: http://root:root@106.15.198.170:7002/eureka/
