spring:
  application:
    name: zuul
server:
  port: 8093

eurekaServer:
  host: localhost
  port: 8761
  user: root
  password: root

eureka:
  client:
    #将此项目注册到Eureka服务
    register-with-eureka: true
    service-url:
      defaultZone: http://${eurekaServer.user}:${eurekaServer.password}@${eurekaServer.host}:${eurekaServer.port}/eureka

#zuul:
#  routes:
#    provider: /User/**

#第二种写法
#zuul:
#   routes:
#     demo:
#       path: /user/**
#       serviceId: provider
#
#第三种写法
#zuul:
#   routes:
#     demo:
#       path: /user/**
#       url: http://localhost:8078/

# 负载均衡
zuul:
  routes:
    demo:
      path: /User/**
      serviceId: provider
provider:
  ribbon:
      listOfServers: http://localhost:8078,http://localhost:8001