spring:
  application:
    name: provider
server:
  port: 8078

eurekaServer:
  host: localhost
  port: 8761
  user: root
  password: root

eureka:
  client:
    #将此项目注册到Eureka服务
    register-with-eureka: true
    service-url:
      defaultZone: http://root:root@localhost:8761/eureka
